# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'beerapi99:$(build.buildId)'
  
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
    
steps:
- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  displayName: 'docker build'
  
