# Generated by Django 2.1.3 on 2018-11-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerList',
            fields=[
                ('beerId', models.AutoField(primary_key=True, serialize=False)),
                ('beerName', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeerTypes',
            fields=[
                ('beerTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('beerType', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='beerlist',
            name='beerType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beerTypeRel', to='api.BeerTypes'),
        ),
    ]
