# Generated by Django 2.1.3 on 2018-11-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beerlist',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='beerlist',
            old_name='date_modified',
            new_name='dateModified',
        ),
        migrations.RenameField(
            model_name='beertypes',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='beertypes',
            old_name='date_modified',
            new_name='dateModified',
        ),
    ]
